backend:
  name: git-gateway
  branch: master
publish_name: editorial_workflow
media_library:
  name: cloudinary
  config:
    cloud_name: dj66cgnpk
    api_key: 884837882467622
    output_filename_only: true
collections:
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    path: "{{year}}/{{slug}}"
    slug: "{{year}}/{{slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["日記"] }
      - { label: "Archives", name: "archives", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Page"
    name: "page"
    files:
      - label: "About"
        name: "about"
        file: "content/about/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About (English)"
        name: "about-en"
        file: "content/about-en/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Product"
        name: "product"
        file: "content/product/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
