backend:
  name: git-gateway
  branch: master
publish_name: editorial_workflow
media_library:
  name: cloudinary
  config:
    cloud_name: dj66cgnpk
    api_key: 884837882467622
    output_filename_only: true
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    path: "{{year}}/{{slug}}"
    slug: "{{year}}/{{slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["日記"] }
      - { label: "Archives", name: "archives", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "other"
    label: "Other"
    folder: "content"
    path: "{{slug}}"
    slug: "{{slug}}"
    create: true
    filter:
      field: tags
      value: ""
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
