backend:
  name: git-gateway
  branch: master
publish_name: editorial_workflow
media_library:
  name: cloudinary
  config:
    cloud_name: dj66cgnpk
    api_key: 884837882467622
    output_filename_only: true
collections:
  - name: "default"
    label: "Default"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "publish-date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "publish-date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["日記"] }
      - { label: "Archives", name: "archives", widget: "list", default: ["{{year}}", "{{year}}/{{month}}"] }
      - { label: "Body", name: "body", widget: "markdown" }
